class071/daily-study

- g0pher/202108.md
- g0pher/README.md
1. Demon 회의
2. KUCIS 프로젝트 회의
3. KUCIS 프로젝트 스캐너 코드 추가
https://github.com/g0pher98/BTS/commit/95d843fa1d10ab1bd48b38a025c3336bafabd27d
> [g0pher] 210822

- neutron/202108.md
1. JPA 강의 들었음.
2. 프로젝트 리뷰 받은 거 리팩토링하고 merge함.
https://github.com/f-lab-edu/jagoga/pull/19
3. 이펙티브 자바 책 7장(스트림)까지 읽음.
> [neutron] 20210821 할일 완료

- neutron/202108.md
* 1. JPA 강의 들었음.
* 2. 프로젝트 리뷰 함.
https://github.com/f-lab-edu/jagoga/pull/18
* 3. 이펙티브 자바 책 8장(메서드)까지 읽음.
> [neutron] 2021/08/22

- neutron/202108.md
1. JPA 강의 들었음. (연관관계)
2. 코테 문제 복기.
https://github.com/oopsys6/algorithm-study/commit/53f69e6248d9e4d4c6847cb5bd3e7a5f3c2435bb
> [neutron] 2021/08/23

- g0pher/202108.md
1. 노원 을지병원에서 CT촬영.
2. 자율주행차 디자인 회의
3. 자율주행차 개발 회의
4. Demon 팀 github 페이지 기존 코드 버리고, 디자인 욕심 버리고 그냥 심플하게 변경
- https://github.com/Demon-KR/Demon-KR.github.io/commit/ec05a2e62
> [g0pher] 2021/08/23

- neutron/202108.md
1. JPA 강의 들었음.
* 고급매핑
* 프록시 연관관계 관리
2. 프로젝트 숙소 등록, 수정 시 유효성 검사 기능 구현
https://github.com/f-lab-edu/jagoga/pull/23
> [neutron] 2021/08/24

- g0pher/202108.md
1. 전산정보원 마지막 근로
2. Demon 팀 github 페이지 각 멤버 card 형태로 분리
https://github.com/Demon-KR/Demon-KR.github.io/commit/24c0f9cd13bf
```
화이자 후기
간지럽다.
```
> [g0pher] 2021/08/27

- neutron/202108.md
1. CS 공부
2. 프로젝트 주소 도메인 구현 후 PR
https://github.com/f-lab-edu/jagoga/pull/28
> [neutron] 2021/08/27

- neutron/202108.md
1. 프로젝트 주소 도메인 bug 수정 및 merge
https://github.com/f-lab-edu/jagoga/commit/81fd57d8d4246355c671892c55a4d071ac2fa813
test 실패했는데 merge 돼서 CI 재구성
2. 프로젝트 Acommodation에 user 권한 추가 issue 생성
3. JPA 강의 듣기
4. 면접 준비
5. 이펙티브 자바 10장까지 보기
1. JPA 강의 듣기
2. Lint 구성 페어 프로그래밍
https://github.com/f-lab-edu/jagoga/pull/32
3. 면접 준비
CS 공부 좀 그만하고 싶다... 
면접 저리가!
> [neutron] 2021/08/28, 2021/08/29

- g0pher/202108.md
1. CTI Korea 연구소장님과 자율주행 연구 관련 전화미팅
2. 자율주행 팀 회의
3. Demon 팀 wormcon 라업 작성  
https://github.com/Demon-KR/Demon-CTF-Writeup/commit/4d10b941079
> [g0pher] 2021/08/30

- g0pher/202108.md
1. 발가락 진료
2. linux kernel exploit 공부([링크](https://github.com/g0pher98/WIL/blob/9a9e45d58608b6ff6f22ca7c3fe207df6ad5e99a/security/linux-kernel-exploit/CVE-2017-11176-part3.md))
https://github.com/g0pher98/WIL/commit/9a9e45d58608b6ff6f
3. KUCIS 프로젝트 회의
> [g0pher] 2021/08/31

- neutron/202108.md
1. 프로젝트 로그인 체크 부분 분석
2. 블로그에 글 작성
* https://oopsys.tistory.com/278
* https://github.com/oopsys6/blog-code/commit/22adef82dca51b730dfeb5b2fcffba40e06ae42f
3. JPA 강의 다 듣기
4. CS 공부
1. cpu bounding 강의
2. JPA 책 읽기
3. 프로젝트 accommodation 도메인에 로그인 권한 기능 추가하기
https://github.com/f-lab-edu/jagoga/pull/35
```
* 빨리 면접 보고 싶다...
* 뭘 준비해야할지 모르겠다.. 
* 개발 열라게 잘하고 싶다!
* 모든 구조가 한번에 떠올라서 개발 뚝딱 했으면 좋겠다.
* 책 한번 읽고 다 이해 + 암기까지 됐으면 좋겠다. 지금은 한 5번 봐도 모르겠다;
* 1일에는 우리 회고 적어야한다.
```
> [neutron] 2021/08/30, 2021/08/31

- neutron/202109.md
1. 자소서 읽기
2. github actions 관련 블로그 글 쓰기
https://oopsys.tistory.com/279
3. JPA 책 읽기
4. 컴공 개별 진로 실강
5. CS 공부
블로그 관련 글 commit 했움!
> [neutron] 2021/09/01

- g0pher/202109.md
1. 블루투스 해킹 - bleedingtooth - badchoice 공격 공부 및 정리 ([링크](https://github.com/g0pher98/WIL/blob/main/security/wireless/bleedingtooth-badchoice.md))
https://github.com/g0pher98/WIL/commit/6d3d36118d7c87c31ebf14a9945
2. 김희열 교수님과 데이트
3. 소중대 서포터즈 SWAT 팀장 대면 회의
1. 데몬팀 페이지 개인링크(sns, blog) 추가  
https://github.com/Demon-KR/Demon-KR.github.io/commit/52c591055ac
2. 금보원 지난 대회 writeup 공부 (내일부터 2주간 대회)
> [g0pher] 2021/09/01, 2021/09/02

- neutron/202109.md
1. CS 공부
2. class 101 강의 듣기
3. 이펙티브 자바 보기
4. JPA 책 읽기
5. 면접 준비
6. 프로젝트 PR
https://github.com/f-lab-edu/jagoga/commit/c8e55136e93e39800b2889b2b43250545e2013fa
1. 면접
2. JPA 깅의 및 책 읽기
3. 프로젝트 테스트 코드 작성 (commit 했으나 아직 merge 안해서 잔디 없음)
면접 끝!!
다들 나의 합격을 응원해줘.
명령이야.
> [neutron] 2021/09/02, 2021/09/03

- neutron/202109.md
1. 프로젝트 PR 후 merge
https://github.com/f-lab-edu/jagoga/commit/ce03ed9c9fb333eb50afc58765da2ce33d6f803e
2. JPA 공부
1. 프로젝트에 JPA 적용
https://github.com/f-lab-edu/jagoga/issues/39
2. 프로젝트 의존성 설정 (아직 merge 안해서 커밋 안보임)
3. JPA 공부
1. 취업했다
2. angularjs 살짝 맛보기
https://github.com/oopsys6/angular-practice
취업했다!!!!!
오늘부터 카카오 맨이다..
너네도 다들 취뽀하기 위해 열심히 공부해라
나는 오늘부터 angularjs 및 spring 판다.
> [neutron] 2021/09/06, 2021/09/07, 2021/09/08

- rookie/202109.md
1. 42서울 1일차 
1. 42서울 2일차 
1. 42서울 3일차 
1. 42서울 4일차 
1. 42서울 5일차 
// exam 
1. 42서울 6일차 
// rush (팀플 진행)
> [rookie] 2021/09/06, 2021/09/07, 2021/09/08, 2021/09/09, 2021/09/10, 2021/09/11

- g0pher/202109.md
*지난 PR에 commit은 되었지만 approve 되지 않은 Day 10, 11 내용도 포함합니다.*
1. 자율주행 프로젝트 5차 테스트 주행 직전 밤샘작업.  
1. K.knock에서 화이트햇 CTF 참여  
확실히 사이버사 문제는 난이도가 높음,,, 그런데도 금방금방 푸는 사람들 보면 갈길이 멀다  
2. Demon팀에서 CSAW 2021 CTF 참여  
CSAW는 문제 나오기만 하면 150팀 정도가 바로 풀어버림,, 대회 규모가 있다보니 더 자극받긴 하는데, 규모에 비해 문제 퀄리티가 좀,,,;; 불-편
*P.S. 강의 지금까지 1개밖에 안들음,,ㅠ 이번 주말에 몰아서 볼예정*
1. CSAW, 화이트햇 2021 CTF 끝
2. 학교 강의 내용 정리
- https://github.com/g0pher98/WIL/commit/b9f3a13b4cd4c35fcb7ab2f3ab5ac12d5cd6f183
> [g0pher] 2021/09/12

- g0pher/202109.md
1. CMS 서비스 취약점 분석
- 제로데이 발견 및 보고서 작성 후 제출(관리자 세션탈취 취약점)   
*(인생 첫 버그바운티 제보)*
> [g0pher] 2021/09/13

- g0pher/202109.md
1. 학교 수업 정리
- https://github.com/g0pher98/WIL/commit/2ea0c1374536764f147eb5ebac37e33a18ca3ca0
> [g0pher] 2021/09/14

- iAm071/202109.md
동아리 알고리즘/자료구조 스터디
https://github.com/we4sley/TIL_071/commit/ec6896d842462676a0f9d20e6888534e93897fef
동아리 알고리즘/자료구조 스터디
백준 17952번 문제 풀이
https://github.com/we4sley/TIL_071/commit/0c14e1f1d82701f02bc6356051c9921c5fc30cc9
> [071] 2021/09/14, 2021/09/15

- g0pher/202109.md
1. 자율주행 2공학관 앞 테스트 주행 시 겪은 오류 정리.
- *ROS랑 python이랑 충돌났는데 이렇게 빡센 python 버전관리는 없었음,,,ㅜㅠ* 
- https://github.com/g0pher98/Oops/commit/11654265b2b31c2c61393795623b1b037e388d48
1. 전날 2공학관 앞에서 테스트 주행 시 수정한 코드 업데이트
- ![image](https://user-images.githubusercontent.com/44149738/133635861-dbed92cc-2384-4b64-bbc4-4beb04844c39.png)
2. CVE-2020-12352 분석 (Linux Bluetooth 취약점 - BleedingTooth - BadChoice)
- https://github.com/g0pher98/WIL/commit/ffb56a559a04056883cadeea4951eb8746875628
- [파일](https://github.com/g0pher98/WIL/blob/ffb56a559a04056883cadeea4951eb8746875628/security/wireless/bleedingtooth-badchoice.md)
> [g0pher] 2021/09/15, 2021/09/16

- iAm071/202109.md
https://github.com/we4sley/TIL_071/commit/b612c61be9772c340cd8fa6087de08396b8acafe
개인 깃허브 잘못 건드려서 오늘 공부한 것도 있고 전에 올렸던 커밋들도 다시 올렸습니다.
> [071] 2021/09/17

- rookie/202109.md
1. 42서울 8일차 
1. 42서울 9일차 
1. 42서울 10일차 
1. 42서울 11일차 
// rush00 카뎃 평가
1. 42서울 12일차 
// rush (팀플 진행)
1. 42서울 13일차 
// exam 
1. 42서울 14일차 
// rush01 (팀플 진행)
> [rookie] 2021/09/12, 2021/09/13, 2021/09/14, 2021/09/15, 2021/09/16, 2021/09/17 

- g0pher/202109.md
1. CVE-2020-12352 분석 (Linux Bluetooth 취약점 - BleedingTooth - BadChoice) 끝냄
- https://github.com/g0pher98/WIL/commit/2c42b8cf0109266e35ad987808f59cd18e8bcad0
- [파일](https://github.com/g0pher98/WIL/blob/main/security/wireless/bleedingtooth-badchoice.md)
2. 블록체인 1주차 강의,,,🥱
- https://github.com/g0pher98/WIL/commit/6a279a9e67b8fe39fbe645ba10bd0fa61e41c221
3. 자율주행 - 초기 센서 연결 시 자동으로 포트 찾는 스크립트 개발
- ![image](https://user-images.githubusercontent.com/44149738/133872443-ec445cc7-5c6a-4f76-9b5c-85e52d0d7ef5.png)
4. h@cktivitycon CTF 2021 참여 (즐겜)
- ![image](https://user-images.githubusercontent.com/44149738/133872511-7d51ef45-e55b-4ae8-83d6-d58e39fa534e.png)
> [g0pher] 2021/09/17

- g0pher/202109.md
1. h@cktivitycon CTF 2021 참여(아래는 오늘 풀이한 문제)
- ![image](https://user-images.githubusercontent.com/44149738/133897141-6fbc328d-6d6c-4dda-abb7-be34161d75ba.png)
- ![image](https://user-images.githubusercontent.com/44149738/133897146-800b0291-79a7-4a2b-87f2-69873fe57748.png)
- ![image](https://user-images.githubusercontent.com/44149738/133897155-f321c382-c7af-47f5-9070-51fa3074de29.png)
- ![image](https://user-images.githubusercontent.com/44149738/133897160-91dacc9b-f832-469b-8500-349d536b5c7b.png)
- ![image](https://user-images.githubusercontent.com/44149738/133897168-f0ba62ff-9c17-483f-8e0b-e28b00cc42cf.png)
- ![image](https://user-images.githubusercontent.com/44149738/133897181-8e3eed29-367a-4be6-9207-24f012850de6.png)
- ![image](https://user-images.githubusercontent.com/44149738/133897189- …
> [g0pher] 2021/09/18

- g0pher/202109.md
1. 네트워크 보안 환경구축 + 2주차 강의 듣기
- https://github.com/g0pher98/WIL/commit/eeab2ab6e6f3ab0aadbcabdc4310688e2043d80e
2. 즐거운 추석~
- ![image](https://user-images.githubusercontent.com/44149738/133944425-1d6bcc3f-f7e4-4256-a6a7-40cb12c752e1.png)
*동생이 DSLR로 찍은 달*
> [g0pher] 2021/09/19

- gray/202109.md
1. angular js 공부하기
https://github.com/graygreat/angular-practice/commit/0eea5eb77f1c619e9bb7be910787bce5342b52b1
1. jagoga 프로젝트 (merge 안해서 commit 안보임)
1. jogoga 프로젝트 구조 설계 변경 및 readme 작성
https://github.com/f-lab-edu/jagoga/pull/48
1. angular js 공부하기
https://github.com/graygreat/angular-practice/commit/62731a395862e96f910d65ce16e79bf4d6c111a3
1. angular js 공부하기
https://github.com/graygreat/angular-practice/commit/5f9a54e14a19f7d59830cebd0905aaf30a9097d3
1. jagoga 프로젝트 pr 및 리팩토링
https://github.com/f-lab-edu/jagoga/pull/49
1. jagoga 프로젝트 리팩토링 (commit 안보임)
취업해서 그런지 공부 시간이 매우 적어졌다...
연휴 끝나고 다시 초심 잡는다. ㅅㄱㅅㄱㅅㄱ
> [gray] 2021/09/14, 2021/09/15, 2021/09/16, 2021/09/17, 2021/09/18, 2021/09/19, 2021/09/20

- g0pher/202109.md
1. 네트워크 보안 3주차 강의 정리
- https://github.com/g0pher98/WIL/commit/898337a33c0c56e48a07b1e4d2de80f54f3b2008
1. 네트워크 보안 과제 
- https://github.com/g0pher98/WIL/commit/4b88261568dad2cc17022ab7b535f235160eb72b
> [g0pher] 2021/09/20, 2021/09/21

- g0pher/202109.md
1. 블록체인 2주차 강의 정리
- https://github.com/g0pher98/WIL/commit/faf6a2b0bf89d2d9f3cea4ca2e06baba658fe81e
- https://github.com/g0pher98/WIL/commit/3023f931a190ad8f0241c11631b247f2658fc177
> [g0pher] 2021/09/22

- g0pher/202109.md
1. 블록체인 3주차 강의 정리
- https://github.com/g0pher98/WIL/commit/751154c5cacf61f6d847d298583b428f4da8100c
2. 블록체인 4주차 강의 정리
- https://github.com/g0pher98/WIL/commit/d6d12ff291c726103239bcce1fc008c2566ef346
3. 아빠 사무실 PC에 ssd 장착해서 window 깔아드리고 작업에 필요한 환경 세팅
> [g0pher] 2021/09/23

- iAm071/202109.md
동아리 알고리즘/자료구조 스터디
https://github.com/we4sley/TIL_071/commit/860ea8c34f065a36688e994ea93123018e08a3b4
> [071] 2021/09/28

- g0pher/202109.md
1. 네트워크 보안 4주차
- https://github.com/g0pher98/WIL/commit/09ea575a1b7b6e3efe2a62565ecb3b3454e6d9b5
2. 아빠 사무실에 CCTV 설치
> [g0pher] 2021/09/24

- g0pher/202110.md
1. 모바일프로그래밍 5주차 정리
- https://github.com/g0pher98/WIL/commit/e3881e3a9cacca360736c5eecd14992abaa0a2ca
2. POX 대회 홈페이지 개발
- ![image](https://user-images.githubusercontent.com/44149738/138599606-592dc4b9-63f1-4e77-b14f-fd6b31adae5d.png)
3. 카카오톡 분석
- 카카오톡 안티디버깅 기능 우회
- ![image](https://user-images.githubusercontent.com/44149738/138599550-c146a122-365f-457c-ae65-83c735a2190f.png)
> [g0pher] 2021/10/24

- iAm071/202110.md
백준 알고리즘 문제 풀이
https://github.com/we4sley/TIL_071/commit/9a5c904184a4d8eaac291cee4552784b60653321
동아리 스터디
https://github.com/we4sley/TIL_071/commit/138c98c2e8b333b509cc3f24125a97b94bd75752
지능웹설계 중간고사
컴퓨터과학개론 중간고사
프로그래머스 레벨1 문제풀이
https://github.com/we4sley/TIL_071/commit/4c8559b2022440e47c97b2df9257ab5cdfd46305
네트워크보안 중간고사
프로그래머스 레벨1 문제풀이
https://github.com/we4sley/TIL_071/commit/476bbacf9fddd5334085f71483b2831930b89bf4
https://github.com/we4sley/TIL_071/commit/c8749df76102c79a7b3bdb34ffaee1eccf70ac15
블록체인플랫폼 중간고사
프로그래머스 레벨1 문제풀이
https://github.com/we4sley/TIL_071/commit/17f73fc6cd87915d6575786c44d2f7e1619f7fe4
프로그래머스 레벨1 문제풀이
https://github.com/we4sley/TIL_071/commit/62c2ddf48b7819f406fef432249aa792efd11125
프로그래머스 레벨1 문제풀이
https://github.com/we4sley/TIL_071/commit/24c1e68358842f5150e1760f18 …
> [071] 2021/10/07, 10/12, 10/20, 10/25, 10/27, 10/28, 10/29, 10/30

- g0pher/202110.md
1. POX 문제 출제
- 출제 과정에서 Flask session을 decoding하는 부분에 대해서 정리하고 싶어서 간단하게 정리
- https://github.com/g0pher98/WIL/commit/07f8ad4337c2cc9c6182e5cc57c093e3a44ee3d5
> [g0pher] 2021/10/25

- g0pher/202110.md
1. 안드로이드 어플리케이션 분석
- ![image](https://user-images.githubusercontent.com/44149738/139458321-ae6b1d8d-c44d-4e9a-9a80-3cbe9258db25.png)
2. 영기집에서 네트워크보안 시험 및 발표 준비
1. 네트워크보안 프로젝트 중간발표
2. 네트워크보안 중간고사
3. 안드로이드 어플리케이션 분석
- 분석 중 frida 정리
- https://github.com/g0pher98/WIL/commit/8649cad30eef2bd263bfcdf90cfcef9a57002b29
1. 블록체인 중간고사
2. 안드로이드 어플리케이션 분석
- wsl2 사용 환경에서 nox 동시 실행 시 hyper-v 호환성 문제 발생. 문서로 정리함.
- https://github.com/g0pher98/WIL/commits?author=g0pher98&since=2021-10-27&until=2021-10-28
> [g0pher] 2021/10/26, 2021/10/27, 2021/10/28

- g0pher/202110.md
1. K.knock KUCIS 활동실적 보고
- 단톡을 백날 공지해도 결국엔 갠톡해서 받아내야 함.
- 하루종일 실적 수집하고 종합하고를 반복.
- 마감 6분전 제출;;;;
- ![image](https://user-images.githubusercontent.com/44149738/139460091-ecb9a666-51b6-4df3-b0a5-b3e1876ec371.png)
> [g0pher] 2021/10/29

- g0pher/202110.md
1. 컴퓨터네트워크 10주차 정리
- https://github.com/g0pher98/WIL/commit/323c943b540f7301cf7cfe0f8fc7159fc5d0d3b9
2. 지능웹설계 8주차 정리
- https://github.com/g0pher98/WIL/commit/e3aad6432544cc49983cbc2b2f077b6bf504941e
3. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- 본격적인 개발을 위한 프로그램 기본 뼈대 구성
- ![image](https://user-images.githubusercontent.com/44149738/139541588-66157c17-7bc2-47f2-9fd0-fd9645a2f0f3.png)
> [g0pher] 2021/10/30

- g0pher/202110.md
1. 지능웹설계 9주차 정리
- https://github.com/g0pher98/WIL/commit/428b7da293909ec5b5c04d0b50e9b0d35ddc721a
2. 여성해킹방어대회(POX) 문제출제
- 웹 문제 시나리오 노선변경 ㅠ
> [g0pher] 2021/10/31

- sunny/[sunny]2110.md
1. 정보처리기사 실기 공부 / 8,9,10,11,12장 정리  
https://github.com/YoonsunC/TIL/commit/ede0b0b160395b1465d0ea92cf1f64b594d4add9  
2. K-Digital Training 수강(AWS 스크립트로 구성 및 ECS 실습)  
https://github.com/YoonsunC/TIL/commit/afee9531b962a02dddc4701094dd3d72d258da1f  
1. 정보처리기사 실기 공부 / 전체정리(하다가 잠들어서 얼마안됨)  
https://github.com/YoonsunC/TIL/commit/f924c2f2e89683de1b03dd2352513a813eda2f54
2. K-Digital Training 수강(AWS NACL, 보안그룹 설정 - NAT Gateway 위주)  
1. 정보처리기사 실기 시험 (내년을 기약)  
2. K-Digital Training 멘토링(최종프로젝트 조원,멘토분들 만남)  
3. 전공탄탄 파이썬 3주차 수강  
https://github.com/YoonsunC/TIL/commit/310457157f6f8c703567e019312f5471925a4018  
4. 형법각론 과제  
1. K-Digital Training 수강(구성도 맞춰서 구성 및 NACL, CIDR 작성)  
https://github.com/YoonsunC/TIL/commit/a1a5df3a2a58c315f7ce44fe25c3268502023a43  
2. 형법각론 중간과제 제출  
1. K-Digital …
> [sunny]  2021/10/14, 10/15, 10/16, 10/19, 10/20, 10/21, 10/22, 10/26

- g0pher/202111.md
1. 여성해킹방어대회(POX) 문제출제
- ![image](https://user-images.githubusercontent.com/44149738/140949816-950a47c3-3559-4295-a0b8-697d22bb5878.png)
2. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- 실제 자동차 ECU 제품 dbc 파일 분석
- 회의 진행
- https://github.com/g0pher98/WIL/commit/855e468b51812b31a960b092e39199a517aa4485
1. 여성해킹방어대회(POX) 문제출제
- 문제 도커화 하는 과정에서 불필요한 삽질을 너무 많이함.
- ![image](https://user-images.githubusercontent.com/44149738/140950759-0d0c9e6a-c482-41f1-8d23-36e423fc694b.png)
1. 여성해킹방어대회(POX) 홈페이지 개발
- ![image](https://user-images.githubusercontent.com/44149738/140958210-e9e6bde5-70ae-47d6-99d7-12f3bd7a41ee.png)
1. 여성해킹방어대회(POX) 홈페이지 개발
- ![image](https://user-images.githubusercontent.com/44149738/140959642-790f0f33-9d5a-4148-a01a-aca1874164b3.png)
> [g0pher] 2021/11/06, 11/07, 11/08, 11/09

- iAm071/202111.md
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/6d2afd99f794f7105756525a8d2b00077d5ed8fb
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/b340c2d905351d9d0dd00172f415bc55aab0eae8
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/301e6fd70872e81ad692e37f129079d8e8c2aa12
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/4f5ba85f5f55e7f53337786f5bbde58b0e419c1e
동아리 알고리즘 스터디 백준 문제풀이
https://github.com/we4sley/TIL_071/commit/e1cf39ed0f2aa41e42897d5be4ecf62b532b9f1a
10월 회고
10월에도 정신 못차리고 커밋 안 해서 벌금이 많이 쌓였는데 11월에는 1일 1커밋을 위해 열심히 노력하고 알고리즘 문제풀이 커밋만이 아니고 공부한 것들도 정리해서 올려보도록 하겠습니다요.....ㅎ
> 2021/11/03, 11/04, 11/05, 11/06, 11/07, 10월 회고

- sunny/[sunny]2111.md
1. K-Digital Training 최종 프로젝트  
2. 전공탄탄 파이썬 5주차 정리  
https://github.com/YoonsunC/TIL/commit/9479ae2396f7f02c63bfc8eb06e0cf1e95dd4353  
1. K-Digital Training 최종 프로젝트  
2. 형법각론 9주차 수강  
3. 네트워크관리사2급 한회차 풀기  
4. 전공탄탄 파이썬 6주차 정리  
https://github.com/YoonsunC/TIL/commit/9a0f8447fb544d2c5a8d681432cacb8e9f7938fd  
1. K-Digital Training 최종 프로젝트  
2. 행정법 9주차 수강  
3. 형법각론 9주차 정리  
https://github.com/YoonsunC/TIL/commit/11ddcfaf51edeb1b5c210d9eb1b916bccefaba5a  
1. K-Digital Training 멘토링  
2. 행정법 9주차 정리  
https://github.com/YoonsunC/TIL/commit/8e89d97849acb7e598080a01a492915cbad2bb3e  
1. 행정법 10주차 수강  
2. 행정법 10주차 정리  
https://github.com/YoonsunC/TIL/commit/40e20db41d4672351e63932103feb61e906a88ef  
1. K-Digital Training 최종 프로젝트  
2. 정보보안 기초 정리(TCP/UDP, NAT, Windows) …
> [sunny] 2021/11/03, 11/04, 11/05, 11/06, 11/08, 11/09, 11/11, 11/12, 11/13, 11/15

- g0pher/202111.md
1. frida 공부
- 안드로이드 앱 후킹하다가 뜬 오류 정리
- https://github.com/g0pher98/Oops/commit/eeebbb1ae202ae7a7d25dc6dfe81862fc4bcdfdc
2. 발가락 진료
- 재수술 확정. 12월 말에 수술하는걸로 날짜잡힘 ㅠ
1. 지능웹 설계 퀴즈
2. SW중심대학 서포터즈
- ![image](https://user-images.githubusercontent.com/44149738/142719875-982b7bf8-89bb-44ea-a176-ad2768777fac.png)
- 태장중학교 실습 기자재 및 교안 준비
- "아두이노를 이용한 스마트 무드등 만들기"
3. K.knock MOU 체결 관련 교수님 면담
4. 경기대학교 에듀테크 강연보조
5. K.knock 회의
- ![image](https://user-images.githubusercontent.com/44149738/142719897-d579868b-e022-4a3b-ad18-f7d638b6f26c.png)
- 세미나 및 MOU 체결 관련
6. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- 한컴 부장님이 과거 프로젝트 자료 보내주셔서 추가 회의 진행
1. 블록체인 과제 비트코인 Balance 구하는 프로그램 개발
- https://github.com/g0pher98/WIL/commit/5dae804fee0fcfcf03a6f2b17b9b45f912138e5f
2. 개별진로발표 수업 사업분석 발표
- "블록체인을 활용한 P2P 대출 서비스"
- 밀린 과제 빡세게 하다보니 발표 준비 많이 …
> [g0pher] 2021/11/16, 17, 18

- g0pher/202111.md
1. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- PCAN 장비에 맞게 코드 수정
- ![image](https://user-images.githubusercontent.com/44149738/142903079-ce3990b9-3db6-4f6d-9fb3-6dfb59b08e9a.png)
2. 블록체인플랫폼 10주차 정리
- https://github.com/g0pher98/WIL/commit/f9a1550a8d16d0624b13fd9b196e0229de9546b6
1. 지능웹설계 10주차 정리
- https://github.com/g0pher98/WIL/commit/fdf7ca8679074b69f52cfb056a0cde41cf403a5d
- https://github.com/g0pher98/WIL/commit/e0f52c44f14658e3eb4ca603174af747cfc4a412
2. 지능웹설계 11주차 정리
- https://github.com/g0pher98/WIL/commit/1f1db360022621aab40f0c6302f6b92274db8db6
1. 지능웹설계 12주차 정리
- https://github.com/g0pher98/WIL/commit/2cd6d38b6da178a098f0400d56c9dd851fe85878
2. 지능웹설계 13주차 정리
- https://github.com/g0pher98/WIL/commit/f5e129710ef179bdc116ae6dc63c9e683fd53837
3. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- …
> [g0pher] 2021/11/20, 21, 22

- g0pher/202111.md
1. K.knock 스터디
2. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- 30일이 최종 발표일이라 거의 매일 만나는듯
- ![image](https://user-images.githubusercontent.com/44149738/143263076-8217bf11-6e04-4958-9a02-110bb0904703.png)
3. 태장중학교 SW 봉사단 교육 준비
- ![image](https://user-images.githubusercontent.com/44149738/143262894-404c534b-4bb6-47a0-be5d-b15fa0f12fe0.png)
1. 태장중학교 SW 봉사
- ![image](https://user-images.githubusercontent.com/44149738/143261991-27188365-c2d2-4933-9bf6-c420c30bfb61.png)
- 경인일보 http://m.kyeongin.com/view.php?key=20211124010004737
- 뉴시스 https://n.news.naver.com/article/003/0010852420
- 한국대학신문 http://news.unn.net/news/articleView.html?idxno=519805
- 대학저널 http://www.dhnews.co.kr/news/articleView.html?idxno=200206
2. 컴퓨터네트워크 11주차 정리
- https://github.com/g0pher98/WIL/commit/48ba1b0d813468ecdfe366e68596e4286058e8ed
3. …
> [g0pher] 2021/11/23, 24

- sunny/[sunny]2111.md
1. K-Digital Training 최종 프로젝트  
2. 전공탄탄 파이썬 8주차 수강  
https://github.com/YoonsunC/TIL/commit/c264ee56d4235b24b8a4e8a3a0ec082a342e72b7   
1. K-Digital Training 최종 프로젝트 - 중간발표준비 ppt 작성  
1. K-Digital Training 최종 프로젝트 - 중간발표준비(디자인 갈아엎음)  
1. 법학과 졸업논문 3차 작성  
(졸업논문인데 왜이렇게 꼼꼼히 읽으시는 겁니까 교수님,,,)  
1. 법학과 졸업논문 3차 작성, 제출  
2. K-Digital Training 최종 프로젝트 - AWS 서비스 상세기능정의서 S3 Glacier 작성  
3. SKCT 공부
> [sunny] 2021/11/17, 11/18, 11/19, 11/22, 11/23

- g0pher/202111.md
1. 지능웹설계 14주차 정리
- https://github.com/g0pher98/WIL/commit/b21e58cd1fd11694f4f2501dbaee7609c5cc6867
2. 모바일프로그래밍 12주차 정리
- https://github.com/g0pher98/WIL/commit/a180f29f8e7a8d8d06b6888ae1b1442ce094f352
3. 모바일프로그래밍 13주차 정리
- https://github.com/g0pher98/WIL/commit/5eae66c962460b5d8efa90759593e4a5aff8b2cf
1. PCR 검사
- 다음주 월요일 유아 대상 봉사 목적.
2. 버그바운티 스터디
- 3 종류 RCE 분석 및 시연
- ![image](https://user-images.githubusercontent.com/44149738/143620389-dc56a204-f3bf-45e5-bee7-f253879de2f5.png)
- race condition 익스 공부
- ![image](https://user-images.githubusercontent.com/44149738/143620458-c877ab21-98ea-4c4d-b5fe-01b93dff2a45.png)
- ![image](https://user-images.githubusercontent.com/44149738/143620480-dbe9730a-5723-44db-9646-bb8c8281c135.png)
> [g0pher] 2021/11/25, 26

- rookie/202111.md
1. libft Part2 modify && Bonus Part start
MelonMania/42_cursus@f4f7cd4
1. 개포 클러스터 프로필 사진 촬영 및 테스트
// 따로 자료가 없어서 출석 시간 사진 첨부
1. libft Bonus Part complete (not tested)
MelonMania/42_cursus@880d211
MelonMania/42_cursus@7111fe1
1. libft Bous Part test 7/9 complete
MelonMania/42_cursus@cda924d
> [rookie] 21/11/21, 22, 23, 25

- g0pher/202111.md
1. 한컴 인텔리전스랑 협업하는 자동차해킹 프로젝트
- GUI 개발 마무리
- ![image](https://user-images.githubusercontent.com/44149738/144235533-1baf6c2a-2a31-4769-8289-26d7358d1b97.png)
- ![image](https://user-images.githubusercontent.com/44149738/144235388-a0cadd5e-9b48-477a-828d-8d6ae0c95eb3.png)
2. SWAT 봉사단
- 비대면 교육 서비스 체험 도움
1. 예비군 원격교육
- 들어보려고 했는데 듣다가 중간에 화생방 파트부터 도망감
2. ZIEN 인턴 회의
3. K.knock 회의
4. 네트워크보안 12주차 정리
- https://github.com/g0pher98/WIL/commit/409ad76abdde010f07a798622f42c49e14e4fe28
5. 네트워크보안 13주차 정리
- https://github.com/g0pher98/WIL/commit/643739bc62936647d244dd8325783912ff896961
1. 경동원 봉사
- ![image](https://user-images.githubusercontent.com/44149738/144240155-2255a5cd-c4a5-4dc5-bb8c-08121e1c3307.png)
2. 상상기업 자율주행팀 발표준비로 밤샘작업,,,
1. SW 페스타 - 상상기업 발표
- 9시 ~ 17시
- …
> [g0pher] 2021/11/27, 28, 29, 30

- iAm071/202111.md
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/18b93803bb7bb58d701bb7a0285798702f3e2c5c
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/ae8ae1590c5fdfe474cbbf81caec1d7171e48a6e
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/83d02236318ca3d8d97c26f0aa1b7ec033e2383d
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/eb83a82d2e6353378e9185a6a7fdef03fa649d93
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/b8194689717ad511d205db7b8114762bd0a38549
HSK 5급 시험
( 이것도 봐주십니까? )
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/bae80f1a28c7fc17b7e3bcc2e51025f4adc1f3f6
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/6fca6ca623963c101500f8555b1765462d091488
프로그래머스 문제풀이
https://github.com/we4sley/TIL_071/commit/444f85d4f3dd4beb95907276952f8e5e62bcaf6b
프로그래머스 문제풀이 …
> [071] 2021/11/08, 10, 13, 14, 15, 20, 21, 22, 23, 24, 26, 27, 28

- sunny/[sunny]2111.md
1. K-Digital Training 최종 프로젝트 - AWS 서비스 상세기능정의서 RDS 작성  
2. 법학과 졸업논문 최종 작성(어쩌면,,졸업,,못할지도,,,?)  
1. K-Digital Training 최종 프로젝트 - AWS 서비스 상세기능정의서 CloudFront 작성  
1. K-Digital Training 최종 프로젝트 - AWS Client VPN에서 ALB로 보낼 수 있는지, S3 접근해보기 등 복구 백업 & RDS 실습  
2. 전공탄탄 파이썬 9주차 수강  
https://github.com/YoonsunC/TIL/commit/9689efbd2e53cc726fe9618eb66d72539fc92d27  
3. SKCT 공부  
1. SKCT시험  
2. 법학과 졸업논문 4차 작성(이미 최종기한이 지났으나 계속 다시 해오라셔서 일주일 연장받음 ㅠ)  
1. 등산 + 법학과 졸업논문 4차 작성 + 엄마 생신겸 외식  
1. 법학과 졸업논문 4차 작성 및 제출(정말 라스트일까?)  
2. 형법각론 12주차 수강 및 정리  
https://github.com/YoonsunC/TIL/commit/ad4db18a6652b6255c23132a4bea00f6e84cf577  
1. K-Digital Training 최종 프로젝트 - AWS Client VPN에서 ALB로 보낼 수 있는지, S3 접근해보기 등 복구 백업 & RDS 실습 및 정리
> [sunny] 2021/11/24, 25, 26, 27, 28, 29, 30

- iAm071/202111.md
인프런 스프링 핵심 원리 강의
https://github.com/we4sley/inflearn-spring-core-principle/commit/a31311b83e52266aa6528bf96dcf235b01faff8b
https://github.com/we4sley/inflearn-spring-core-principle/commit/8d354121eb281801ae3241cb90d8f687ca62cbc9
https://github.com/we4sley/inflearn-spring-core-principle/commit/a8e79edb850a3f59f789a54e841e7a301eeba59c
https://github.com/we4sley/inflearn-spring-core-principle/commit/2eb719cd8957e6a644aa983e460c0126e3c84f00
https://github.com/we4sley/inflearn-spring-core-principle/commit/eacd97a49060a6b3189542932f7dc4bd86f63edd
프로그래머스 문제풀이
https://github.com/we4sley/TIL-071/commit/dcb58f69309b366303b706262f708738581b4030
생각만큼은 그렇게 열심히 하지 않은거 같지만 이제 점점 공부하는 습관이 안정되는거 같아서 다행이라고 생각한다. 곧 종강도 하니까 내 공부에 더 집중하고 열심히 나아가야겠다. 학교 수업을 열심히 듣지도 않았는데 학교 수업 핑계로 덜 열심히 공부한거 같아 조금 아쉬운 부분이 있다. …
> [071] 2021/11/29, 11/30, 11월 회고

- iAm071/202111.md
- iAm071/202112.md
이러닝 무대화술 시험
프로그래머스 문제풀이
https://github.com/we4sley/TIL-071/commit/087f1e61ac5dac027f7fb6c6cccfcd8cb80a16b9
인프런 스프링 핵심 원리 강의
https://github.com/we4sley/inflearn-spring-core-principle/commit/26b72b996a69672d05832252ebe43590b0060c7d
https://github.com/we4sley/inflearn-spring-core-principle/commit/2fc88f8adf02d53fb2ef3385fc4cd226cd406c03
https://github.com/we4sley/inflearn-spring-core-principle/commit/815885ddf575dd74fefe1ca50e67125a30a94923
https://github.com/we4sley/inflearn-spring-core-principle/commit/c1898f58e0bd44693b760dc02a840a9a2cbe7b90
https://github.com/we4sley/inflearn-spring-core-principle/commit/f4cd5690be90ff1bcff016adfd0e803c43f4758f
https://github.com/we4sley/inflearn-spring-core-principle/commit/2a3d1b5dff6fb507dae3aa4dbf915d8c04b85e9b
이러닝 이미지, 생활 속의 수학 시험
프로그래머스 문제풀이 …
> [071] 2021/12/02, 03, 04, 05, 06, 07, 08, 09, 10

- g0pher/202112.md
1. 모바일프로그래밍 프로젝트
- 교내 전자문진 애플리케이션 KGU PASS 개발
- https://github.com/g0pher98/kgu-selfcheck/commit/14a95f3ee426260f733bea9fab2287aec85b70a9
- https://github.com/g0pher98/kgu-selfcheck/commit/7b83619a47030b4bdbdba6d99b9ad19c63d37b92
- https://github.com/g0pher98/kgu-selfcheck/commit/7ce4420cf486740c0901c56eeae3c8affe61bb20
- https://github.com/g0pher98/kgu-selfcheck/commit/f42dc2c6afeb3896f1a27de9b6fc3b8720a81c48
- https://github.com/g0pher98/kgu-selfcheck/commit/e2289204a116d8ecce02efbb5e0a96691d206756
- https://github.com/g0pher98/kgu-selfcheck/commit/e3e6463822bc843b15a9581f10a7c5b857b84e70
- https://github.com/g0pher98/kgu-selfcheck/commit/b4da95449148a49fba73d1ced6804e665d5ff134
1. 모바일프로그래밍 프로젝트
- 교내 전자문진 애플리케이션 KGU PASS 개발
- https://github.com/g0pher98/kgu-selfcheck/commit/cc71dec43292c …
> [g0pher] 2021/12/10, 11, 12

- iAm071/202112.md
인프런 스프링 핵심 원리 강의
https://github.com/we4sley/inflearn-spring-core-principle/commit/cde27b5153d782efa9e9d54f2d0be698a76a8cd3
https://github.com/we4sley/inflearn-spring-core-principle/commit/872bc9c582ffc0519b3d6a32f73689e982a63e99
https://github.com/we4sley/inflearn-spring-core-principle/commit/e2ea7a6448ce5b066dadd9102dafcf3380458624
https://github.com/we4sley/inflearn-spring-core-principle/commit/38193994d085ff2a1b2c1eb34f40803b71b0f729
https://github.com/we4sley/inflearn-spring-core-principle/commit/b36d0cc02813dc949e3aeeab62161f461a882a11
인프런 스프링 핵심 원리 강의
https://github.com/we4sley/inflearn-spring-core-principle/commit/68454417854bfc0fd64815215055c7e609a7a16b
https://github.com/we4sley/inflearn-spring-core-principle/commit/115c062ea5d827c12db065563890159516e5d61d …
> [071] 2021/12/11, 12, 13, 14, 15, 16, 19, 20, 21
